### ISSUE TITLE
feat(merge): task list for Weaver collaboration/merge epic

### ISSUE THREAD

**Issue by izuru0** [hyperledger/cactus#2037]
### Description 
The issue #1522 describes the goals for Weaver collaboration/merge. However it isn’t particularly clear about what are the things that need to be identified/decided in architecture level in order to satisfy the goals at the end of collaboration/merge effort. In other words, I want a list of tasks that set the direction of merged code. 

Task list: 

- [x] Add one or more Weaver maintainers to the Cactus maintainers’ list 
- [x] Copy weaver source code to cactus source tree 
- [x] Incorporate common data structures from Weaver code into Cactus Core 
- [ ] Incorporate Weaver Relay module into the Cactus Connector (ongoing) 
- [ ] Identify all interoperability modes presently supported by either or both projects (Here I am assuming ‘interoperability modes’ means how Weaver/Cactus user interacts with Weaver/Cactus codes, e.g. importing a cactus api-client modules to interact with ledgers or by directly importing connectors, etc.)  
- [ ] Determine how Inter-network communication should be done: Cactus connectors and Weaver relays either merged into a standard “network router” or co-existing and interoperable 
- [ ] Build common libraries, preferrably by refactoring existing code

**Comment by takeutak** [comment]
Thanks for creating a draft of task lists.  I'd like to add one item about business logic plugin using Cactus and Weaver
#2028

**Comment by izuru0** [comment]
I'm closing this issue, following discussion with maintainers
items listed here should be created as independent issues
